# Generated by Django 6.1.1 on 2026-09-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fitnessprofile",
            name="experience_level",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                    ("elite", "Elite"),
                ],
                default="beginner",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="fitnessprofile",
            name="activity_level",
            field=models.CharField(
                choices=[
                    ("sedentary", "Sedentary"),
                    ("light", "Lightly Active"),
                    ("moderate", "Moderately Active"),
                    ("very_active", "Very Active"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="fitnessprofile",
            name="goal",
            field=models.CharField(
                choices=[
                    ("weight_loss", "Weight Loss"),
                    ("muscle_gain", "Muscle Gain"),
                    ("fat_loss", "Fat Loss"),
                    ("strength", "Strength"),
                    ("general_fitness", "General Fitness"),
                ],
                max_length=30,
            ),
        ),
    ]
