# Generated by Django 6.1.1 on 2026-10-02 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0002_fitnessprofile_experience_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutplan",
            name="schedule",
            field=models.TextField(blank=True),
        ),
    ]
